version: "3"
services:
  api:
    image: job-offer-backend
    build: .
    networks:
      - backend
    ports:
      - "8080:8080"

  web-cli:
    image: job-offer-backend
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
